services:
  ecf2:
    image: ${DOCKER_REGISTRY-}ecf2
    build:
      context: .
      dockerfile: ECF2/Dockerfile
    depends_on:
      - sqlserverdb
      
  sqlserverdb:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=T0pS€cr€tP@ssw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    build:
      context: Database
      dockerfile: Dockerfile

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    # restart: always
    environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: T0pS€cr€tP@ssw0rd
    volumes:
      - mongovolume:/data/db


volumes:
  sqlvolume:
  mongovolume: